llm:
  port: 9000

  models:
    # -------------------------
    # Default model + routing + fallback
    # -------------------------
    - name: gpt-5.5-pro
      provider: openAI
      params:
        model: gpt-5.5-pro
        apiKey: ${OPENAI_API_KEY}
      matches:
        # analysis.*
        - headers:
            - name: X-Task
              value:
                exact: analysis
          name: gemini-3.5-flash

        # code.*
        - headers:
            - name: X-Task
              value:
                exact: code
          name: gpt-5.5

        # vision.*
        - headers:
            - name: X-Task
              value:
                exact: vision
          name: gemini-3-flash-preview

        # local.*
        - headers:
            - name: X-Task
              value:
                exact: local
          name: gemma-4-26b-a4b-it

        # Fallback chain
        - headers: []
          name: gpt-5.5
        - headers: []
          name: gpt-4.1
        - headers: []
          name: gemini-3.5-flash
        - headers: []
          name: gemma-4-26b-a4b-it



    # -------------------------
    # OpenAI Models
    # -------------------------
    - name: gpt-5.5
      provider: openAI
      params:
        model: gpt-5.5
        apiKey: ${OPENAI_API_KEY}

    - name: gpt-4.1
      provider: openAI
      params:
        model: gpt-4.1
        apiKey: ${OPENAI_API_KEY}

    - name: gpt-4.1-mini
      provider: openAI
      params:
        model: gpt-4.1-mini
        apiKey: ${OPENAI_API_KEY}

    - name: gpt-4.1-nano
      provider: openAI
      params:
        model: gpt-4.1-nano
        apiKey: ${OPENAI_API_KEY}

    - name: gpt-4o
      provider: openAI
      params:
        model: gpt-4o
        apiKey: ${OPENAI_API_KEY}

    - name: gpt-4o-mini
      provider: openAI
      params:
        model: gpt-4o-mini
        apiKey: ${OPENAI_API_KEY}

    # -------------------------
    # Gemini Models
    # -------------------------
    - name: gemini-3.5-flash
      provider: gemini
      params:
        model: gemini-3.5-flash
        apiKey: ${GEMINI_API_KEY}

    - name: gemini-3.1-pro-preview
      provider: gemini
      params:
        model: gemini-3.1-pro-preview
        apiKey: ${GEMINI_API_KEY}

    - name: gemini-3-flash-preview
      provider: gemini
      params:
        model: gemini-3-flash-preview
        apiKey: ${GEMINI_API_KEY}

    - name: gemini-3.1-flash-lite
      provider: gemini
      params:
        model: gemini-3.1-flash-lite
        apiKey: ${GEMINI_API_KEY}

    # -------------------------
    # Local OpenAI-compatible models
    # -------------------------
    - name: gemma-4-26b-a4b-it
      provider: openAI
      params:
        model: gemma-4-26b-a4b-it
        apiKey: "none"
        hostOverride: "localhost:11434"
        pathPrefix: /v1

    - name: gemma-4-12b-it
      provider: openAI
      params:
        model: gemma-4-12b-it
        apiKey: "none"
        hostOverride: "localhost:11434"
        pathPrefix: /v1

    - name: gemma-4-e4b-it
      provider: openAI
      params:
        model: gemma-4-e4b-it
        apiKey: "none"
        hostOverride: "localhost:11434"
        pathPrefix: /v1

    - name: gemma-4-e2b-it
      provider: openAI
      params:
        model: gemma-4-e2b-it
        apiKey: "none"
        hostOverride: "localhost:11434"
        pathPrefix: /v1

logging:
  level: info
  format: json


binds:
- port: 15010
  listeners:
  - protocol: HTTP
    name: listener
    routes:
    - backends:
      - mcp:
          targets:
          - name: mcp-registry
            openapi:
              host: https://registry.modelcontextprotocol.io
              schema:
                url: https://raw.githubusercontent.com/sheldonrobinson/studious-sniffle/refs/heads/main/openapi/mcp-registry-api.json
          - name: countries
            openapi:
              schema:
                url: https://raw.githubusercontent.com/sheldonrobinson/studious-sniffle/refs/heads/main/openapi/countries.json
              host: https://restcountries.com
          - name: country-is
            openapi:
              schema:
                url: https://raw.githubusercontent.com/sheldonrobinson/studious-sniffle/refs/heads/main/openapi/country-is.json
              host: https://api.country.is/
          - name: ip-geolocation
            openapi:
              schema:
                url: https://raw.githubusercontent.com/sheldonrobinson/studious-sniffle/refs/heads/main/openapi/ipapi-is.json
              host: https://api.ipapi.is
          - name: my-ip
            openapi:
              schema:
                url: https://raw.githubusercontent.com/sheldonrobinson/studious-sniffle/refs/heads/main/openapi/myip-com.json
              host: https://api.myip.com
          - name: surise-sunset
            openapi:
              schema:
                url: https://raw.githubusercontent.com/sheldonrobinson/studious-sniffle/refs/heads/main/openapi/sunrise-sunset.json
              host: https://api.sunrise-sunset.org
          - name: uv-index
            openapi:
              schema:
                url: https://raw.githubusercontent.com/sheldonrobinson/studious-sniffle/refs/heads/main/openapi/current-uv-index.json
              host: https://currentuvindex.com/api/v1
          - name: weather
            openapi:
              schema:
                url: https://raw.githubusercontent.com/sheldonrobinson/studious-sniffle/refs/heads/main/openapi/open-meteo.json
              host: https://api.open-meteo.com
          - name: holidays
            openapi:
              host: https://date.nager.at
              schema:
                url: https://raw.githubusercontent.com/sheldonrobinson/studious-sniffle/refs/heads/main/openapi/date-nager-api-v3.json
          statefulMode: stateless
      name: registry
      policies:
        cors:
          allowOrigins:
          - '*'
          allowHeaders:
          - '*'
          exposeHeaders:
          - Mcp-Session-Id
- port: 15011
  listeners:
  - protocol: HTTP
    name: listener
    routes:
    - backends:
      - mcp:
          targets:
          - name: jobicy
            openapi:
              host: https://jobicy.com
              schema:
                url: https://raw.githubusercontent.com/sheldonrobinson/studious-sniffle/refs/heads/main/openapi/jobicy.json
          - name: jobrise
            openapi:
              host: https://api.jobrise.io
              schema:
                url: https://raw.githubusercontent.com/sheldonrobinson/studious-sniffle/refs/heads/main/openapi/jobrise.json
          statefulMode: stateless
      name: careers
      policies:
        cors:
          allowOrigins:
          - '*'
          allowHeaders:
          - '*'
          exposeHeaders:
          - Mcp-Session-Id
- port: 15012
  listeners:
  - protocol: HTTP
    name: listener
    routes:
    - backends:
      - mcp:
          targets:
          - name: books
            openapi:
              schema:
                url: https://openlibrary.org/static/openapi.json
              host: https://openlibrary.org
          - name: met-museum
            openapi:
              schema:
                url: https://raw.githubusercontent.com/sheldonrobinson/studious-sniffle/refs/heads/main/openapi/metmuseum.json
              host: https://collectionapi.metmuseum.org/public/collection/v1
          - name: musicbrainz
            openapi:
              schema:
                url: https://raw.githubusercontent.com/sheldonrobinson/studious-sniffle/refs/heads/main/openapi/musicbrainz.json
              host: https://musicbrainz.org/ws/2
          - name: song-lyrics
            openapi:
              schema:
                url: https://raw.githubusercontent.com/sheldonrobinson/studious-sniffle/refs/heads/main/openapi/lrclib.json
              host: https://lrclib.net
          - name: tv-movies
            openapi:
              schema:
                url: https://raw.githubusercontent.com/sheldonrobinson/studious-sniffle/refs/heads/main/openapi/tvmaze-com.json
              host: https://api.tvmaze.com
          statefulMode: stateless
          prefixMode: always
      name: culture
      policies:
        cors:
          allowOrigins:
          - '*'
          allowHeaders:
          - '*'
          exposeHeaders:
          - Mcp-Session-Id
